[package]
name = "eigenplayer"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.17.1"
mlua = { version = "0.11.6", features = ["lua54", "async", "macros"] }
symphonia = "0.5.5"
wgpu = "28.0.0"
winit = "0.30.12"
